### ISSUE TITLE
add onboarding

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/pure#1]
### They plainly asked for it

> I think it's better to have more instructions of how to use this service. Cause I didn't know how to use it until I played it for like 10 mins 
> I would say, if there are more instructions, and easier way to set the "site" field, it would be even better. - Rachel

### Get confused
>> Nope, you have your master password and compute the app/website (see #4 for details)

> but every time I open the site, the fingerprint changes, so I won't be able to know what password (lesspass's result) I use on the site I want to login (ex, gmail), right?

**Comment by guillaumevincent** [comment]
This issue was moved to lesspass/lesspass#13
